### ISSUE TITLE
Subissue: Endpoint for menus

### ISSUE THREAD

**Issue by oviyaseeniraj** [ucsb-cs156-f24/proj-dining-f24-14#14]
**Inherits from #42** 
Backend 2

Create a service that will get all of the menu items served in a particular dining commons for a particular meal on a particular date.
Using the api endpoint described here: https://developer.ucsb.edu/apis/dining/dining-menu

Then build a controller endpoint GET /api/diningcommons/:date-time/:dining-commons-code/:meal that returns this information.

### User Story
As a user of the dining commons app,
I want to view the menu items for a specific dining commons, meal, and date,
So that I can see what is being served and decide what I want to eat.

**Comment by pconrad** [comment]
@oviyaseeniraj please update this issue to be specific about which of these five original issues it comes from: #39 #40 #41 #42  and/or #43 

Please also improve the description.

In particular, please add a user story to explain the role of this this new controller endpoint in addressing a user need. 

What is the user story that requires us to build this service and this controller?  Always *start* with that, and *then* describe what you are building in the code to support that.  If this is a first step towards something that will be in the frontend, explain what the frontend feature will be that references this backend endpoint.
