### ISSUE TITLE
Subissue: Frontend 3 - Placeholder page for individual dining commons

### ISSUE THREAD

**Issue by Refinnej04** [ucsb-cs156-f24/proj-dining-f24-14#15]
**Inherits from #39** 
## Frontend 3: Placeholder page for individual dining commons

Create a placeholder page at the url `/diningcommons/:diningCommonsCode` that will originally show the title `Placeholder for Dining Commons Page for {diningCommonsCode}`

Add this into App.js so that the links from the Home Page work and take you to the placeholder page.

**Comment by pconrad** [comment]
@Refinnej04 please update this issue to be specific about which of these five original issues it comes from: https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/39 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/40 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/41 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/42 and/or https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/43
