### ISSUE TITLE
Subissue: Frontend 4 - Add placeholder page /moderate accessible only to admins and link in menu bar as "Moderate"

### ISSUE THREAD

**Issue by rionapampati** [ucsb-cs156-f24/proj-dining-f24-14#16]
# Frontend 4

Inherits from #41 

## Description
This issue adds a new placeholder page `/moderate` that is accessible only to admins and linked in the menu bar under the label "Moderate." The purpose of this page is to serve as a dedicated space for admins to manage and moderate user reviews. By providing this page, admins can efficiently approve or reject reviews to ensure appropriate content on the platform, maintaining its integrity and usability.

## What Placeholder Page?
The `/moderate` page will act as a central hub for admins to view and moderate user reviews. It will initially be a placeholder but will later include features such as a review table with options for approving or rejecting reviews, as well as status updates.

## User Story
- **As an admin**, I can access a dedicated moderation page to review all submitted user reviews so that I can ensure the platform remains free from inappropriate content.  

## Why Do They Need a Review Table on This Page?
The review table will organize all submitted reviews, making it easy for admins to see their details, such as content, rating, and user-submitted comments. This is critical for efficiently moderating content, with features to approve or reject reviews directly from the table.

## Why Is `deleteColumn=true` in This Case, and What Does That Mean?
The `deleteColumn=true` flag is not applicable in this case since the focus of the `/moderate` page is on approving or rejecting reviews rather than allowing admins to delete them. Instead, moderation-specific options like "Approve" and "Reject" will be implemented.

## Frontend 4: Add placeholder page /moderate accessible only to admins and link in menu bar as "Moderate" (taken directly from EPIC)

blank

**Comment by pconrad** [comment]
@rionapampati please update this issue to be specific about which of these five original issues it comes from: https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/39 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/40 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/41 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/42 and/or https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/43

And please include a description. The description should be stand alone (and not depend on the title for context), and explain what is being changed, added, deleted in this issue, and most importantly, *why* from a user perspective.

You may copy text from the issues 39-43.  What you can't do is just leave this blank.
