### ISSUE TITLE
Subissue: Modify endpoint for menus

### ISSUE THREAD

**Issue by amanpdesai** [ucsb-cs156-f24/proj-dining-f24-14#20]
**Inherits from #42** 
Backend 3

Modify the endpoint that retrieves menu items to so that each time a menu item is retreived, a record for that menu item is stored in a new database table with these fields:

- id
- DiningCommonsCode
- Meal
- Item Name
- Station

Ensure that there are no duplicates in this table; every combination of DiningCommonsCode, Meal, Item Name and Station should be unique.

This id number will form the basis of efficient retrieval of reviews for particular menu items later.

Modify the endpoint so that the id is returned along with each menu item. This may require a data transfer object (ask for details, or look up DTOs.)

**Comment by pconrad** [comment]
@Aman   please update this issue to be specific about which of these five original issues it comes from: https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/39 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/40 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/41 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/42 and/or https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/43
