### ISSUE TITLE
Subissue: Controller methods to post reviews (all users), get all reviews (admin only)

### ISSUE THREAD

**Issue by Va1a** [ucsb-cs156-f24/proj-dining-f24-14#32]
**Inherits from #40** 
Backend 2 "Controller methods to post reviews (all users), get all reviews (admin only)"
Creates a controller method to post reviews (all users).
This method will be located at /api/reviews/post 
All users will have access to this endpoint.

Creates a controller method to get all reviews (admins only)
This method will be located at /api/reviews/all
Only admin users will have access to this endpoint.

These methods will be located in ReviewsController.java

**Comment by pconrad** [comment]
@Va1a please update this issue to be specific about which of these five original issues it comes from: #39 #40 #41 #42  and/or #43 

And make a much better issue description.  This is way too vague.  Copy from the original issue if needed.
