### ISSUE TITLE
Subissue: Frontend 2 - Create a ReviewTable component that shows all reviews

### ISSUE THREAD

**Issue by rionapampati** [ucsb-cs156-f24/proj-dining-f24-14#9]
# Frontend 2

Inherits from #41 

## User Stories for the My Reviews Table

- **As a user**, I can see and manage my reviews (edit or delete) to keep them up to date.  
- **As an admin**, I can approve or reject reviews to ensure inappropriate content is filtered out.  
- **As a user**, I can track the status of my reviews to know if they’re approved, rejected, or pending.  

## Relevant Pages and Features

1. **My Reviews Page (`/myreviews`)**  
   - Displays review details (item, stars, review, status, moderator comments).  
   - Provides options to edit or delete reviews.  

2. **Admin Moderation Page**  
   - Includes "Approve" and "Reject" options for reviews when moderation is enabled.  
   - Tracks review status updates after moderation.  

3. **Menu Item Page**  
   - Lists all reviews for a menu item to help users decide what to eat.  

## Feature Rationale

- **Review Details**: Keeps users informed about their submissions and feedback.  
- **Edit/Delete Options**: Enables users to fix mistakes or remove reviews.  
- **Moderation Features**: Supports admins in maintaining a clean and relevant database.  

## Frontend 2 from EPIC

Create a ReviewTable component that shows all reviews in the format returned by the backend endpoint described in #5 for retreiving reviews by user.

It should have an optional columns for "Approve" and "Reject" that appear only if a flag "moderatorOptions" is passed as true in the props to the component.

it should also have a Delete column available only if deleteColumn=true is passed.

**Comment by pconrad** [comment]
@rionapampati please update this issue to be specific about which of these five original issues it comes from: #39 #40 #41 #42  and/or #43 

Please also improve the description.

What is/are the user stories that this table will support?  What pages will it eventually be included on, and what will those pages enable users or admins to accomplish?  Why does it need each of the features described here?
